audio:
  Azure:
    service_region: SERVICE_REGION
    speech_key: SPEECH_KEY
  Ali:
    access_key_id: ACCESS_KEY_ID
    access_key_secret: ACCESS_KEY_SECRET
    app_key: APP_KEY
  Tencent:
    access_key_id: ACCESS_KEY_ID
    access_key_secret: ACCESS_KEY_SECRET
    app_key: APP_KEY
  provider: Azure

captioning:
  provider: Azure

llm:
  DeepSeek:
    api_key: YOUR_API_KEY
    base_url: https://api.deepseek.com/
    model_name: deepseek-chat
  Baichuan:
    api_key: YOUR_API_KEY
    model_name: Baichuan3-Turbo
  Moonshot:
    api_key: YOUR_API_KEY
    model_name: moonshot-v1-8k
  Tongyi:
    api_key: YOUR_API_KEY
    model_name: qwen-turbo
  OpenAI:
    api_key: YOUR_API_KEY
    model_name: gpt-3.5-turbo
  Azure:
    api_key: YOUR_API_KEY
    base_url: http://base.url.openai
    model_name: null
  Qianfan:
    api_key: YOUR_API_KEY
    secret_key: YOUR_SK_KEY
    model_name: ERNIE-Bot-turbo
  provider: Moonshot
resource:
  pexels:
    api_key: API_KEY
  pixabay:
    api_key: API_KEY
  provider: pexels
ui:
  language: zh-CN
video:

test_mode: False

publisher:
  driver_type: chrome
  content_location:
  driver_location:
  auto_publish: True
  common:
    enable: True
    title_prefix: 标题前缀
    collection: 集合名称
    tags:
  douyin:
    enable: True
    title_prefix: 标题前缀
    collection: 集合名称
  kuaishou:
    enable: True
    title_prefix: 标题前缀
    collection: 集合名称
    domain:
      enable: True
      level1: 教育
      level2: 语言教育
  xiaohongshu:
    enable: True
    title_prefix: 标题前缀
    collection: 集合名称
  shipinhao:
    enable: True
    title_prefix: 标题前缀
    collection: 集合名称

